name: show output context

on: push

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show output context
        run: echo "${{ toJson(github) }}"